- name: Comment Pull Request
  uses: thollander/actions-comment-pull-request@v2.5.0
  if: github.repository == 'makersacademy/makersbnb-python-seed'
  with:
    message: |
      :warning: **You've created this pull request against the template repository.** Please close this PR, and recreate it within your forked repository.
