name: Comment Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.repository == 'makersacademy/makersbnb-python-seed'
    steps:
      - uses: thollander/actions-comment-pull-request@v2.5.0
        with:
          message: |
            :warning: **You've created this pull request against the template repository.** Please close this PR, and recreate it within your forked repository.
